Remove Ruby 1.9.3 support, add testing on 2.3/2.4
sensu-plugins/sensu-plugins-hbase pull request #4
Opened 2017-07-11 20:37 UTC by Evesy

## Pull Request Checklist

RE https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/27

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose

Remove 1.9.3 as it is no longer supported.
Add testing on 2.3.0 & 2.4.1

#### Known Compatablity Issues

Breaking change for users on Ruby 1.9.3

2017-07-12 03:13 UTC, eheydrick requested changes
two small cleanup items otherwise looks good.

2017-07-12 03:13 UTC, eheydrick commented on sensu-plugins-hbase.gemspec
>  # pvt_key = '~/.ssh/gem-private_key.pem'
remove this.

2017-07-12 03:13 UTC, eheydrick commented on sensu-plugins-hbase.gemspec
>    # s.signing_key            = File.expand_path(pvt_key) if $PROGRAM_NAME =~ /gem\z/
and this.

2017-07-13 03:42 UTC, majormoses approved these changes
LGTM

2017-07-13 03:42 UTC, merged

2017-07-13 03:54 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-hbase/versions/1.0.0